import {StyleSheet} from 'react-native';
import {Colors} from '../../Utilities/Styles/colors';
import fontFamily from '../../Utilities/Styles/fontFamily';
import {
  moderateScale,
  moderateScaleVertical,
} from '../../Utilities/Styles/responsiveSize';

const styles = StyleSheet.create({
  username: {
    fontSize: 20,
    fontWeight: '700',
    color: Colors.navyblue,
    fontFamily: fontFamily.regular,
    marginLeft: 20,
  },
  searchcon: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: 30,
    paddingHorizontal: 20,
    shadowColor: Colors.black,
    shadowOpacity: 0.1,
    shadowOffset: {width: 0, height: 2},
    elevation: 2,
    height: 50,
    marginHorizontal: 20,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: Colors.black,
    fontFamily: fontFamily.regular,
    paddingLeft: 10,
  },
  separator: {
    height: moderateScaleVertical(20),
    width: 1,
    backgroundColor: Colors.black,
    marginHorizontal: 10,
  },
  filterIconContainer: {
    padding: 8,
  },
  card: {
    marginHorizontal: 10,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: Colors.white,
    shadowColor: Colors.black,
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    width: '100%',
  },
  image: {
    width: '100%',
    height: '100%',
  },
  overlay: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    padding: 20,
  },
  title: {
    color: Colors.navyblue,
    fontSize: 12,
    fontWeight: '600',
    fontFamily: fontFamily.regular,
  },
  button: {
    marginTop: 12,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 30,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: Colors.white,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  buttonText: {
    color: Colors.white,
    fontWeight: '600',
    fontSize: 12,
    fontFamily: fontFamily.regular,
  },
  daytxt: {
    backgroundColor: Colors.white,
    borderRadius: 36,
    paddingVertical: 5,
    position: 'absolute',
    top: 10,
    left: 10,
    paddingHorizontal: 10,
  },
  tabcontainer: {
    width: moderateScaleVertical(25),
    height: moderateScale(25),
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.white,
    position: 'absolute',
    top: 10,
    right: 10,
  },
  preferencetxt: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: fontFamily.regular,
    color: Colors.white,
    textAlign: 'center',
  },
  promtxt: {
    fontSize: 12,
    fontWeight: '400',
    fontFamily: fontFamily.regular,
    color: Colors.white,
    textAlign: 'center',
    width: '85%',
  },
  tripplan: {
    backgroundColor: Colors.navyblue,
    width: '100%',
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 39,
  },
  promotionalcon: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
  },
  outerview: {
    marginHorizontal: 20,
    padding: 15,
    backgroundColor: Colors.white,
    borderRadius: 5,
    marginVertical: 10,
  },
  vectorcon: {
    width: 30,
    height: 30,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.white,
    top: 5,
    right: 5,
    alignSelf: 'flex-end',
  },
  traveltxt: {
    fontSize: 14,
    fontWeight: '700',
    fontFamily: fontFamily.regular,
    color: Colors.navyblue,
  },
  arrowcon: {
    width: moderateScaleVertical(36),
    height: moderateScale(36),
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primaryblue,
  },
  durationtxt: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: fontFamily.regular,
    color: Colors.secondaryfont,
    marginTop: 2,
  },
  filtertxt: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    fontWeight: '400',
    color: Colors.white,
  },
});

export default styles;
