import {Profile} from '../../Navigation';

export default {
  AppLogo: require('../../Assets/Images/Loading.png'),
  Onboarding: require('../../Assets/Images/onboarding.png'),
  Onboardingone: require('../../Assets/Images/onboarding1.png'),
  Onboardingtwo: require('../../Assets/Images/onboarding2.png'),
  Evolution: require('../../Assets/Images/evolution.png'),
  backClick: require('../../Assets/Images/backbtn.png'),
  Profile: require('../../Assets/Images/profile.png'),
  Feed: require('../../Assets/Images/feed.png'),
  Filter: require('../../Assets/Images/filter.png'),
  Search: require('../../Assets/Images/search.png'),
  Cross: require('../../Assets/Images/cross.png'),
  City: require('../../Assets/Images/city.png'),
  Home: require('../../Assets/Images/home.png'),
  Blueback: require('../../Assets/Images/blueback.png'),
  Cart: require('../../Assets/Images/cart.png'),
  Cartoon: require('../../Assets/Images/cartoon.png'),
  Girl: require('../../Assets/Images/girl.png'),
  Upload: require('../../Assets/Images/upload.png'),
  Edit: require('../../Assets/Images/edit.png'),
  Call: require('../../Assets/Images/call.png'),
  Location: require('../../Assets/Images/location.png'),
  Mail: require('../../Assets/Images/mail.png'),
  Preference: require('../../Assets/Images/preference.png'),
  Support: require('../../Assets/Images/support.png'),
  Policy: require('../../Assets/Images/policy.png'),
  Insurance: require('../../Assets/Images/insurance.png'),
  House: require('../../Assets/Images/house.png'),
  Flight: require('../../Assets/Images/flight.png'),
  jahaaj: require('../../Assets/Images/jahaaj.png'),
  Boat: require('../../Assets/Images/boat.png'),
};
