export default {
  SplashScreen: 'SplashScreen',
  OnBoarding: 'OnBoarding',
  LoginScreen: 'LoginScreen',
  RegisterScreen: 'RegisterScreen',
  ForgotPassword: 'ForgotPassword',
  OtpScreen: 'OtpScreen',
  UpdatePassword: 'UpdatePassword',
  HomeScreen: 'HomeScreen',
  TabRoutes: 'TabRoutes',
  Explore: 'Explore',
  Feed: 'Feed',
  Wishlist: 'Wishlist',
  Profile: 'Profile',
  EditProfile: 'EditProfile',
  MyBookings: 'MyBookings',
  Support: 'Support',
  PrivacyPolicy: 'PrivacyPolicy',
  BookingSummary: 'BookingSummary',
  Cart: 'Cart',
  PackageDetail: 'PackageDetail',
};
